# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: "rj_sms"
version: "1.0.0"
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: "default"

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target" # directory which will store compiled SQL files
clean-targets: # directories to be removed by `dbt clean`
  - "target"
  - "dbt_modules"

# Defining variables
vars:
  TAG_CPF: 'projects/rj-sms/locations/us/taxonomies/7948647440833323337/policyTags/7275937608331929015'
  TAG_CNS: 'projects/rj-sms/locations/us/taxonomies/7948647440833323337/policyTags/8199751371890630153'
  TAG_NOME: 'projects/rj-sms/locations/us/taxonomies/4827881364676585191/policyTags/2632983500029416584'
  TAG_TELEFONE: 'projects/rj-sms/locations/us/taxonomies/4827881364676585191/policyTags/6197099915332240403'
  TAG_EMAIL: 'projects/rj-sms/locations/us/taxonomies/4827881364676585191/policyTags/6775173897032728488'
  TAG_ENDERECO: 'projects/rj-sms/locations/us/taxonomies/6217643325435375844/policyTags/5348387254077392279'
  TAG_CRM: 'projects/rj-sms/locations/us/taxonomies/7948647440833323337/policyTags/2129975481142765086'
  TAG_MATERIAL:  'projects/rj-sms/locations/us/taxonomies/6217643325435375844/policyTags/7956417154094178470'
  TAG_DTNASCIMENTO: 'projects/rj-sms/locations/us/taxonomies/6217643325435375844/policyTags/674367858357103255'  
  TAG_DTOBITO: 'projects/rj-sms/locations/us/taxonomies/6217643325435375844/policyTags/6268958505478592114'
  TAG_NATURALIDADE: 'projects/rj-sms/locations/us/taxonomies/6217643325435375844/policyTags/2018842376178907296'
  TAG_OBITO: 'projects/rj-sms/locations/us/taxonomies/6217643325435375844/policyTags/3126519816284522145'
  TAG_DADOS_CLINICOS: 'projects/rj-sms/locations/us/taxonomies/4827881364676585191/policyTags/8216812064277366977'
  TAG_EXAME_IMAGEM: 'projects/rj-sms/locations/us/taxonomies/4827881364676585191/policyTags/2271001638601718755'
  TAG_EXAME_LABORATORIO: 'projects/rj-sms/locations/us/taxonomies/4827881364676585191/policyTags/7774875538975783665'
  TAG_NOME_MAE: 'projects/rj-sms/locations/us/taxonomies/4827881364676585191/policyTags/2411979615060611545'
  TAG_NOME_PAI: 'projects/rj-sms/locations/us/taxonomies/4827881364676585191/policyTags/8262940514454666213'
  TAG_COREN: 'projects/rj-sms/locations/us/taxonomies/7948647440833323337/policyTags/1950446664324638402'
  TAG_MEDICAMENTO: 'projects/rj-sms/locations/us/taxonomies/6217643325435375844/policyTags/3872480936078888207'



# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  +persist_docs:
    relation: true
    columns: true
    elementary:
      +schema: "elementary"
  rj_sms:
    # all models should have unique and not null
    +required_tests: {"unique.*|not_null": 2}
    +required_docs: true
    raw:
      +materialized: table
      cnes_web:
        +schema: brutos_cnes_web
      cnes_ftp:
        +schema: brutos_cnes_ftp
      estoque_central_tpc:
        +schema: brutos_estoque_central_tpc
      plataforma_smsrio:
        +schema: brutos_plataforma_smsrio
      prontuario_vitacare:
        +schema: brutos_prontuario_vitacare
      prontuario_vitai:
        +schema: brutos_prontuario_vitai
      sheets:
        +schema: brutos_sheets
    intermediate:
        +materialized: ephemeral
    marts:
        +materialized: table
        core:
          dimensions:
            +schema: saude_dados_mestres
          facts:
            +schema: saude_estoque
        dengue:
            +schema: projeto_dengue
        estoque:
            +schema: projeto_estoque
        reprocessamento:
            +schema: controle_reprocessamento
tests:
  rj_sms:
    +severity: error
    +store_failures: true