# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: "rj_sms"
version: "1.0.0"
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: "default"

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target" # directory which will store compiled SQL files
clean-targets: # directories to be removed by `dbt clean`
  - "target"
  - "dbt_modules"

# Defining variables
vars:
  TAG_CPF: 'projects/rj-sms/locations/us/taxonomies/1484589960313336167/policyTags/2725924647574340150'
  TAG_CNS: 'projects/rj-sms/locations/us/taxonomies/1484589960313336167/policyTags/8466642122276519749'
  TAG_NOME: 'projects/rj-sms/locations/us/taxonomies/1484589960313336167/policyTags/6704834904025032692'
  TAG_TELEFONE: 'projects/rj-sms/locations/us/taxonomies/1484589960313336167/policyTags/4821430283459568091'
  TAG_EMAIL: 'projects/rj-sms/locations/us/taxonomies/1484589960313336167/policyTags/7952571888021215204'
  TAG_ENDERECO: 'projects/rj-sms/locations/us/taxonomies/1484589960313336167/policyTags/4420561030199075247'
  TAG_CRM: 'projects/rj-sms/locations/us/taxonomies/1484589960313336167/policyTags/3383058637162172795'
  TAG_MATERIAL:  'projects/rj-sms/locations/us/taxonomies/1484589960313336167/policyTags/3196241456602174733'

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  +persist_docs:
    relation: true
    columns: true
    elementary:
      +schema: "elementary"
  rj_sms:
    # all models should have unique and not null
    +required_tests: {"unique.*|not_null": 2}
    +required_docs: true
    raw:
      +materialized: table
      cnes_web:
        +schema: brutos_cnes_web
      cnes_ftp:
        +schema: brutos_cnes_ftp
      estoque_central_tpc:
        +schema: brutos_estoque_central_tpc
      prontuario_vitacare:
        +schema: brutos_prontuario_vitacare
      prontuario_vitai:
        +schema: brutos_prontuario_vitai
      sheets:
        +schema: brutos_sheets
    intermediate:
        +materialized: ephemeral
    marts:
        +materialized: table
        core:
          dimensions:
            +schema: saude_dados_mestres
          facts:
            +schema: saude_estoque
        estoque:
            +schema: projeto_estoque
        treinamento:
            +schema: projeto_treinamento
tests:
  rj_sms:
    +severity: error
    +store_failures: true