# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: "rj_sms"
version: "1.0.0"
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: "default"

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target" # directory which will store compiled SQL files
clean-targets: # directories to be removed by `dbt clean`
  - "target"
  - "dbt_modules"

# Defining variables
vars:
  # internal variables
  DBT_USER: "{{ env_var('DBT_USER', 'dev_fantasma') }}"
  # policy tags
  TAG_CPF: 'projects/rj-sms/locations/us/taxonomies/7948647440833323337/policyTags/7275937608331929015'
  TAG_CNS: 'projects/rj-sms/locations/us/taxonomies/7948647440833323337/policyTags/8199751371890630153'
  TAG_RG: 'projects/rj-sms/locations/us/taxonomies/7948647440833323337/policyTags/1359518576511941019'
  TAG_NOME: 'projects/rj-sms/locations/us/taxonomies/4827881364676585191/policyTags/2632983500029416584'
  TAG_TELEFONE: 'projects/rj-sms/locations/us/taxonomies/4827881364676585191/policyTags/6197099915332240403'
  TAG_EMAIL: 'projects/rj-sms/locations/us/taxonomies/4827881364676585191/policyTags/6775173897032728488'
  TAG_ENDERECO: 'projects/rj-sms/locations/us/taxonomies/6217643325435375844/policyTags/5348387254077392279'
  TAG_CRM: 'projects/rj-sms/locations/us/taxonomies/7948647440833323337/policyTags/2129975481142765086'
  TAG_MATERIAL:  'projects/rj-sms/locations/us/taxonomies/6217643325435375844/policyTags/7956417154094178470'
  TAG_DTNASCIMENTO: 'projects/rj-sms/locations/us/taxonomies/6217643325435375844/policyTags/674367858357103255'  
  TAG_DTOBITO: 'projects/rj-sms/locations/us/taxonomies/6217643325435375844/policyTags/6268958505478592114'
  TAG_NATURALIDADE: 'projects/rj-sms/locations/us/taxonomies/6217643325435375844/policyTags/2018842376178907296'
  TAG_OBITO: 'projects/rj-sms/locations/us/taxonomies/6217643325435375844/policyTags/3126519816284522145'
  TAG_DADOS_CLINICOS: 'projects/rj-sms/locations/us/taxonomies/4827881364676585191/policyTags/8216812064277366977'
  TAG_EXAME_IMAGEM: 'projects/rj-sms/locations/us/taxonomies/4827881364676585191/policyTags/2271001638601718755'
  TAG_EXAME_LABORATORIO: 'projects/rj-sms/locations/us/taxonomies/4827881364676585191/policyTags/7774875538975783665'
  TAG_NOME_MAE: 'projects/rj-sms/locations/us/taxonomies/4827881364676585191/policyTags/2411979615060611545'
  TAG_NOME_PAI: 'projects/rj-sms/locations/us/taxonomies/4827881364676585191/policyTags/8262940514454666213'
  TAG_COREN: 'projects/rj-sms/locations/us/taxonomies/7948647440833323337/policyTags/1950446664324638402'
  TAG_MEDICAMENTO: 'projects/rj-sms/locations/us/taxonomies/6217643325435375844/policyTags/3872480936078888207'
  TAG_IDENTIFICADOR: 'projects/rj-sms/locations/us/taxonomies/7948647440833323337/policyTags/3220112556547044825'
  TAG_DADOS_BANCARIOS: 'projects/rj-sms/locations/us/taxonomies/7948647440833323337/policyTags/7203052192415747676'



# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  +persist_docs:
    relation: true
    columns: true
  elementary:
    +schema: "gerenciamento__dbt_elementary"
    +enabled: "{{ target.name in ['prod'] }}"
  rj_sms:
    # all models should have unique and not null
    +required_tests: {"unique.*|not_null": 2}
    +required_docs: true
    raw:
      +materialized: table
      +tags: "raw"
      cnes_web:
        +schema: brutos_cnes_web
        +tags: "weekly"
        +labels:
          dado_publico: sim
          dado_pessoal: sim
          dado_anonimizado: nao
          dado_sensivel_saude: nao
      cnes_ftp:
        +schema: brutos_cnes_ftp
        +tags: "weekly"
        +labels:
          dado_publico: sim
          dado_pessoal: sim
          dado_anonimizado: nao
          dado_sensivel_saude: nao
      datasus:
        +schema: brutos_datasus
        +tags: "weekly"
        +labels:
          dado_publico: sim
          dado_pessoal: sim
          dado_anonimizado: nao
          dado_sensivel_saude: nao
      estoque_central_tpc:
        +schema: brutos_estoque_central_tpc
        +tags: "daily"
        +labels:
          dado_publico: nao
          dado_pessoal: nao
          dado_anonimizado: nao
          dado_sensivel_saude: nao
          dominio: estoque
      historico_clinico_integrado:
        +schema: brutos_historico_clinico_integrado
        +tags: "daily"
        +labels:
          dado_publico: nao
          dado_pessoal: sim
          dado_anonimizado: nao
          dado_sensivel_saude: sim
          dominio: historico_clinico
      plataforma_smsrio:
        +schema: brutos_plataforma_smsrio
        +tags: ["smsrio", "daily"]
        +labels:
          dado_publico: nao
          dado_pessoal: nao
          dado_anonimizado: nao
          dado_sensivel_saude: nao
      prontuario_vitacare:
        +schema: brutos_prontuario_vitacare
        +tags: ["vitacare", "daily"]
        +labels:
          dado_publico: nao
          dado_pessoal: sim
          dado_anonimizado: nao
          dado_sensivel_saude: sim
          dominio: historico_clinico
      prontuario_vitai:
        +schema: brutos_prontuario_vitai
        +tags: "vitai"
        +labels:
          dado_publico: nao
          dado_pessoal: sim
          dado_anonimizado: nao
          dado_sensivel_saude: sim
          dominio: historico_clinico
      osinfo:
        +schema: brutos_osinfo
        +tags: "daily"
        +labels:
          dado_publico: nao
          dado_pessoal: nao
          dado_anonimizado: nao
          dado_sensivel_saude: nao
      seguir_em_frente:
        +schema: brutos_seguir_em_frente
        +tags: "daily"
        +labels:
          dado_publico: nao
          dado_pessoal: sim
          dado_anonimizado: nao
          dado_sensivel_saude: sim
      sheets:
        +schema: brutos_sheets
        +tags: "daily"
        +labels:
          dado_publico: nao
          dado_pessoal: nao
          dado_anonimizado: nao
          dado_sensivel_saude: nao
      sih:
        +schema: brutos_sih
        +tags: "daily"
        +labels:
          dado_publico: nao
          dado_pessoal: nao
          dado_anonimizado: nao
          dado_sensivel_saude: nao
    intermediate:
        +materialized: ephemeral
        historico_clinico:
          +tags: ["hci", "daily"]
          +labels:
            dado_publico: nao
            dado_pessoal: sim
            dado_anonimizado: nao
            dado_sensivel_saude: sim
            dominio: historico_clinico
          paciente:
            +tags: ["paciente"]
    marts:
        +materialized: table
        core:
          +tags: "core"
          dimensions:
            +schema: saude_dados_mestres
            +labels:
              dado_publico: nao
              dado_pessoal: nao
              dado_anonimizado: nao
              dado_sensivel_saude: nao
          facts:
            sisreg:
              +schema: saude_sisreg
              +tags: "daily"
              +labels:
                dado_publico: nao
                dado_pessoal: nao
                dado_anonimizado: nao
                dado_sensivel_saude: nao
            estoque:
              +schema: saude_estoque
              +tags: "daily"
              +labels:
                dado_publico: nao
                dado_pessoal: sim
                dado_anonimizado: nao
                dado_sensivel_saude: sim
                dominio: estoque
        dengue:
            +schema: projeto_dengue
            +tags: "daily"
        estoque:
            +schema: projeto_estoque
            +tags: ["daily", "estoque"]
            +labels:
              dado_publico: nao
              dado_pessoal: sim
              dado_anonimizado: nao
              dado_sensivel_saude: sim
              dominio: estoque
        gerenciamento:
            +tags: "daily"
        historico_clinico:
            +tags: ["daily", "hci"]
            +labels:
              dado_publico: nao
              dado_pessoal: sim
              dado_anonimizado: nao
              dado_sensivel_saude: sim
              dominio: historico_clinico
        historico_clinico_app:
            +tags: ["daily", "hci_app"]
            +labels:
              dado_publico: nao
              dado_pessoal: sim
              dado_anonimizado: nao
              dado_sensivel_saude: sim
              dominio: historico_clinico
        seguir_em_frente:
            +schema: projeto_seguir_em_frente
            +tags: "daily"
            +labels:
              dado_publico: nao
              dado_pessoal: sim
              dado_anonimizado: nao
              dado_sensivel_saude: sim
              dominio: seguir_em_frente

tests:
  rj_sms:
    +severity: error
    +store_failures: true
    +schema: gerenciamento__dbt_test_audit

seeds:
  rj_sms:
    estoque:
      +schema: projeto_estoque

# flags:
#   require_explicit_package_overrides_for_builtin_materializations: False
#   source_freshness_run_project_hooks: True
