default:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: rj-sms-dev
      dataset: dbt
      location: US
      threads: 6
      keyfile: /tmp/credentials.json
    prod:
      type: bigquery
      method: service-account
      project: rj-sms
      dataset: dbt
      location: US
      threads: 6
      keyfile: /tmp/credentials.json