default:
  target: devlocal
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: rj-sms-dev
      dataset: dbt
      location: US
      threads: 2
      keyfile: /credentials-dev/dev.json
    prod:
      type: bigquery
      method: service-account
      project: rj-sms
      dataset: dbt
      location: US
      threads: 2
      keyfile: /credentials-prod/prod.json
    devlocal:
      type: bigquery
      method: service-account
      project: rj-sms-dev
      dataset: dbt
      location: US
      threads: 2
      keyfile: /home/thiagotrabach/.credentials/rj-sms-dev-a8fd4239a9eb.json
    compile:
      type: bigquery
      method: service-account
      project: rj-sms-dev
      dataset: dbt
      location: US
      threads: 2
      keyfile: credentials/dev.json
