default:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: rj-sms-dev
      dataset: gerenciamento__dbt
      location: US
      threads: 6
      keyfile: C:\Users\home\.credentials\rj-sms-dev-a8fd4239a9eb.json
    prod:
      type: bigquery
      method: service-account
      project: rj-sms
      dataset: gerenciamento__dbt
      location: US
      threads: 6
      keyfile: C:\Users\home\.credentials\rj-sms-f0dc62a2b7d5.json
