default:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: rj-sms-dev
      dataset: gerenciamento__dbt
      location: US
      threads: 6
      keyfile: C:\Users\home\.credentials\rj-sms-dev-6b9be4537ca1.json
    prod:
      type: bigquery
      method: service-account
      project: rj-sms
      dataset: gerenciamento__dbt
      location: US
      threads: 6
      keyfile: C:\Users\home\.credentials\rj-sms-dev-6b9be4537ca1.json
    compile:
      type: bigquery
      method: service-account
      project: rj-sms-dev
      dataset: gerenciamento__dbt
      location: US
      threads: 6
      keyfile: C:\Users\home\.credentials\rj-sms-dev-6b9be4537ca1.json
