name: DBT Compile

on: [pull_request]

jobs:
  dbt-compile:
    name: DBT Compile
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Create credentials directory
      run: mkdir -p credentials

    - name: Mount credentials
      env:
        DBT_CREDENTIALS_DEV: ${{ secrets.DBT_CREDENTIALS_DEV }}
      run: echo "$DBT_CREDENTIALS_DEV" > /tmp/credentials.json

    - name: Ler campo do JSON
      run: |
        JSON_VALUE=$(jq -r '.client_email' /tmp/credentials.json)
        echo "A conta de serviço é: $JSON_VALUE"

    - name: Install dbt
      run:  pip install dbt-core dbt-bigquery setuptools

    - name: Install DBT Dependencies
      run:  dbt deps

    - name: Compile dbt models
      run: dbt compile --profiles-dir . --profile sms --target dev

