name: DBT Create Command

on:
  pull_request:
    types: [synchronize, opened, reopened]

jobs:
  dbt_run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Get changed files
        id: files
        uses: Ana06/get-changed-files@v2.1.0
      
      - name: Create DBT Run Command
        id: create-dbtrun-command
        continue-on-error: true
        run: |
          python .github/workflows/scripts/create_dbt_run_command.py "${{ steps.files.outputs.all }}"

      - name: Delete previous comments
        uses: izhangzhihao/delete-comment@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          delete_user_name: github-actions[bot]
          issue_number: ${{ github.event.number }}

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: "${{ steps.code-tree-analysis.outputs.pr-message }}"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
